debug: false
#Actuator 숨겨진 기능 모두 활성화
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.board.project: debug
    org.springframework.web.servlet: debug
#    jpa 로그를  debug 레벨로 관찰 할 수 있는데, 안에 들어가는 바인딩 파라미터를 보여준다.
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
#    test 데이터베이스 데이터 생성할 수 있게 도와줌
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      #스프링이 지원하지 않는 hibernate 기능 사용
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    open-in-view:
  h2.console.enabled: false
  sql.init.mode: always
  #thymeleaf.cache: false
  data.rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb